name: GitHub Actions Demo App

on:
  push:
    branches: [main]

jobs:
  unit-tests:
    name: Run Test On PR
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Xcode
      run: sudo xcode-select --switch /Applications/Xcode_16.0.app

    - name: Build
      run: xcodebuild -scheme GitHubActionsPractice -destination 'platform=iOS Simulator,name=iPhone 15,OS=18.0'

    - name: Run Tests
      run: xcodebuild -scheme GitHubActionsPractice -destination 'platform=iOS Simulator,name=iPhone 15,OS=18.0' test
